name: Typelevel.scala
description: Let the Scala compiler work for you. We provide type classes, instances, conversions, testing, supplements to the standard library, and much more.
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
  events:
    output: true
    permalink: /event/:path/
    layout: event
  projects:
    output: false

email: info@typelevel.org
gitter: //gitter.com
google_groups: //google.com
code_of_conduct: //code.of.conduct.com