name: Typelevel.scala
description: Let the Scala compiler work for you. We provide type classes, instances, conversions, testing, supplements to the standard library, and much more.
twitter: typelevel
email: info@typelevel.org
gitter: //gitter.com
google_groups: //google.com

# Configurations
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty
paginate: 10
paginate_path: "/blog/:num/"

gems: [jekyll-paginate]

collections:
  events:
    output: true
    permalink: /event/:path/
    layout: event
  projects:
    output: false

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title.html
      relative_permalinks: false